# Generated by Django 5.0.6 on 2024-07-14 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0002_event_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
