# Generated by Django 5.0.6 on 2024-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0003_alter_comment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juicerecipe',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
