# Generated by Django 5.0.6 on 2024-07-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0005_alter_juicerecipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juicerecipe',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
