# Generated by Django 5.0.6 on 2024-07-15 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0006_alter_juicerecipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='event',
        ),
        migrations.AddField(
            model_name='review',
            name='juice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='juices_app.juicerecipe'),
        ),
    ]
