# Generated by Django 5.0.6 on 2024-07-15 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0007_remove_review_event_review_juice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='juice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='juices_app.juicerecipe'),
        ),
    ]
