# Generated by Django 5.0.6 on 2024-07-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0008_alter_review_juice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment',
        ),
    ]
