# Generated by Django 5.0.6 on 2024-07-15 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juices_app', '0009_remove_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='juice',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='juices_app.event'),
            preserve_default=False,
        ),
    ]
